// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "camera.ecs.cpp" 

using namespace ecs;

static void default_init_camera_component_internal(Event* event, ComponentsAccessor& accessor)
{
  const ecs::OnEntityCreated* casted_event = reinterpret_cast<const ecs::OnEntityCreated*>(event);
  const const TransformComponent& root_tm = accessor.get<const TransformComponent>(compile_ecs_name_hash("root_tm"));
  CameraComponent& camera = accessor.get<CameraComponent>(compile_ecs_name_hash("camera"));
  default_init_camera_component(*casted_event, root_tm,camera);
}


static EventSystemRegistration default_init_camera_component_registration(
  default_init_camera_component_internal,
  compile_ecs_name_hash("OnEntityCreated"),
  {
    DESCRIBE_QUERY_COMPONENT("root_tm", const TransformComponent),
    DESCRIBE_QUERY_COMPONENT("camera", CameraComponent)
  },
  "default_init_camera_component"
);
