// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "decal.ecs.cpp" 

using namespace ecs;

static void default_init_decal_component_internal(Event* event, ComponentsAccessor& accessor)
{
  const ecs::OnEntityCreated* casted_event = reinterpret_cast<const ecs::OnEntityCreated*>(event);
  const TransformComponent& root_tm = accessor.get<TransformComponent>(compile_ecs_name_hash("root_tm"));
  DecalComponent& decal = accessor.get<DecalComponent>(compile_ecs_name_hash("decal"));
  default_init_decal_component(*casted_event, root_tm,decal);
}


static EventSystemRegistration default_init_decal_component_registration(
  default_init_decal_component_internal,
  compile_ecs_name_hash("OnEntityCreated"),
  {
    DESCRIBE_QUERY_COMPONENT("root_tm", TransformComponent),
    DESCRIBE_QUERY_COMPONENT("decal", DecalComponent)
  },
  "default_init_decal_component"
);
