// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "static_mesh.ecs.cpp" 

using namespace ecs;

static void default_init_mesh_component_internal(Event* event, ComponentsAccessor& accessor)
{
  const ecs::OnEntityCreated* casted_event = reinterpret_cast<const ecs::OnEntityCreated*>(event);
  const TransformComponent& root_tm = accessor.get<TransformComponent>(compile_ecs_name_hash("root_tm"));
  StaticMeshComponent& static_mesh = accessor.get<StaticMeshComponent>(compile_ecs_name_hash("static_mesh"));
  default_init_mesh_component(*casted_event, root_tm,static_mesh);
}


static EventSystemRegistration default_init_mesh_component_registration(
  default_init_mesh_component_internal,
  compile_ecs_name_hash("OnEntityCreated"),
  {
    DESCRIBE_QUERY_COMPONENT("root_tm", TransformComponent),
    DESCRIBE_QUERY_COMPONENT("static_mesh", StaticMeshComponent)
  },
  "default_init_mesh_component"
);
