// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "imgui_render.ecs.cpp" 

using namespace ecs;

static void imgui_render_prepare_internal(Event* event, ComponentsAccessor& accessor)
{
  const Engine::OnBeforeRender* casted_event = reinterpret_cast<const Engine::OnBeforeRender*>(event);
  Engine::Render::ImGuiRender& imgui_render = accessor.get<Engine::Render::ImGuiRender>(compile_ecs_name_hash("imgui_render"));
  imgui_render_prepare(*casted_event, imgui_render);
}


static EventSystemRegistration imgui_render_prepare_registration(
  imgui_render_prepare_internal,
  compile_ecs_name_hash("OnBeforeRender"),
  {
    DESCRIBE_QUERY_COMPONENT("imgui_render", Engine::Render::ImGuiRender)
  },
  "imgui_render_prepare"
);
