#pragma once

/*   SOURCE     */

const char* const SourceTemplate = 
R"T(
/*
   THIS FILE WAS GENERATED BY REFLECTION HEADER TOOL
   DO NOT MODIFY IT BY YOURSELF
   OR SOMETHING TERRIBLE WILL HAPPEN TO MY TEAMMATE IN CS GO 
*/
#include <{{{CLASS_HEADER}}}>

{{{CLASS_IMPL_IMPLEMENTATION_LIST}}}

{{{CLASS_IMPL_USAGE_LIST}}}
)T";


const char* GetClassImplImplementationTemplate =
R"T(
template<>
const Meta::Class* Meta::TypeAccessor::GetClassImpl<{{{CLASS_TYPE}}}>(TypeTag<{{{CLASS_TYPE}}}>)
{
  static Meta::ClassStorage<{{{CLASS_ATTRIBUTES_NUMBER}}}> cs{[](auto& cs) {
    {{{CLASS_ATTRIBUTES_LIST}}}
  }};

  const static Meta::Class c{ 
                        "{{{CLASS_TYPE}}}",
                        sizeof( {{{CLASS_TYPE}}} ),
                        "{{{CLASS_HEADER}}}",
                        cs.attributes,
                        {{{CLASS_ATTRIBUTES_NUMBER}}} };

  static bool isRegistered = false;
  if (!isRegistered)
  {
    Meta::MetaStorage* storage = Meta::MetaStorage::Instance();
    storage->RegisterClass(&c, "{{CLASS_TYPE}}" );
    isRegistered = true;
  }

  return &c;
}

)T";

const char* ClassAttributeTemplate =
R"T(
  cs.attributes[{{{ATTRIBUTE_INDEX}}}].type = Meta::TypeAccessor::GetType<{{{ATTRIBUTE_TYPE_NAME}}}>();
  cs.attributes[{{{ATTRIBUTE_INDEX}}}].offset = offsetof({{{CLASS_TYPE}}}, {{{CLASS_ATTRIBUTE_NAME}}});
  cs.attributes[{{{ATTRIBUTE_INDEX}}}].name = "{{{CLASS_ATTRIBUTE_NAME}}}";
)T";

const char* const  ClassImplUsageTemplate = 
R"T(
const Meta::Class* {{{CLASS_TYPE}}}::StaticClass = Meta::TypeAccessor::GetClassImpl<{{{CLASS_TYPE}}}>(Meta::TypeTag<{{{CLASS_TYPE}}}>{});
)T";

/*   HEADER     */

const char* const HeaderTemplate =
R"T(
/*
   THIS FILE WAS GENERATED BY REFLECTION HEADER TOOL
   DO NOT MODIFY IT BY YOURSELF
   OR SOMETHING TERRIBLE WILL HAPPEN TO MY TEAMMATE IN CS GO 
*/

{{#HAS_NAMESPACE}}
namespace {{{CLASS_NAMESPACE}}} { class {{{CLASS_NAME}}}; }
{{/HAS_NAMESPACE}}

{{^HAS_NAMESPACE}}
class {{{CLASS_NAME}}};
{{/HAS_NAMESPACE}}

{{{CLASS_IMPL_DECLARATION_LIST}}}
)T";


const char* const GetClassImplUsageDeclarationTemplate =
R"T(
template<>
const Meta::Class* Meta::TypeAccessor::GetClassImpl<{{{CLASS_TYPE}}}>(TypeTag<{{{CLASS_TYPE}}}>);
)T";