// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "indirect_light_ta.ecs.cpp" 

using namespace ecs;

//Engine::OnFrameGraphInit handler
static
void mk_fg_node_gibs_indirect_light_ta(Event*, ComponentsAccessor&)
{
  fg::register_node("gibs_indirect_light_ta", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    const uint2 __renderSize__ = reg.getRenderSize();


    auto gibs_indirect_light_variance = reg.createTexture("gibs_indirect_light_variance",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R8_UNORM,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_UAV | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::ShaderReadWrite,
      false
    );


    auto gibs_indirect_light_ta_target = reg.createTexture("gibs_indirect_light_ta_target",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R32G32B32A32_S,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_UAV | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::ShaderReadWrite,
      false
    );


    auto gibs_indirect_light_ta_history = reg.createTexture("gibs_indirect_light_ta_history",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R32G32B32A32_S,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_UAV | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::ShaderReadWrite,
      false
    );

    auto gibs_indirect_light_ta_history_prev = reg.readTexture("gibs_indirect_light_ta_history", gapi::TextureState::ShaderRead, fg::Timeline::Previous);
    auto gibs_indirect_light_variance_prev = reg.readTexture("gibs_indirect_light_variance", gapi::TextureState::ShaderRead, fg::Timeline::Previous);
    fg::dsl::AccessDecorator render_size{__renderSize__};
    auto gibs_indirect_light_sample = reg.readTexture("gibs_indirect_light_sample", gapi::TextureState::ShaderRead, false);
    auto motionBuf = reg.readTexture("motionBuf", gapi::TextureState::ShaderRead, false);
    auto late_opaque_depth = reg.readTexture("late_opaque_depth", gapi::TextureState::DepthReadStencilRead, false);
    auto gbuf1 = reg.readTexture("gbuf1", gapi::TextureState::ShaderRead, false);
    auto late_opaque_depth_prev = reg.readTexture("late_opaque_depth", gapi::TextureState::DepthReadStencilRead, fg::Timeline::Previous);
    auto gbuf1_prev = reg.readTexture("gbuf1", gapi::TextureState::ShaderRead, fg::Timeline::Previous);

    return [gibs_indirect_light_variance,gibs_indirect_light_variance_prev,gibs_indirect_light_ta_target,gibs_indirect_light_ta_history_prev,gibs_indirect_light_sample,motionBuf,late_opaque_depth,gbuf1,late_opaque_depth_prev,gbuf1_prev,render_size](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("varianceOutput", gibs_indirect_light_variance.get());
      tfx::set_extern("varianceHistory", gibs_indirect_light_variance_prev.get());
      tfx::set_extern("taOutput", gibs_indirect_light_ta_target.get());
      tfx::set_extern("taHistory", gibs_indirect_light_ta_history_prev.get());
      tfx::set_extern("inputIrradiance", gibs_indirect_light_sample.get());
      tfx::set_extern("motionBuf", motionBuf.get());
      tfx::set_extern("gbuffer_depth", late_opaque_depth.get());
      tfx::set_extern("gbuffer_normal", gbuf1.get());
      tfx::set_extern("gbuffer_depth_prev", late_opaque_depth_prev.get());
      tfx::set_extern("gbuffer_normal_prev", gbuf1_prev.get());
      gibs_indirect_light_temporal_acc(encoder, render_size.get());
    };
  });
}

static
EventSystemRegistration mk_fg_node_gibs_indirect_light_ta_registration(
  mk_fg_node_gibs_indirect_light_ta,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_gibs_indirect_light_ta"
);
