// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "surfels_find_alloc_pos.ecs.cpp" 

using namespace ecs;

//Engine::OnFrameGraphInit handler
static
void mk_fg_node_gibs_surfels_find_surfels_alloc_pos(Event*, ComponentsAccessor&)
{
  fg::register_node("gibs_surfels_find_surfels_alloc_pos", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    const uint2 __renderSize__ = reg.getRenderSize();

    fg::dsl::AccessDecorator render_size{__renderSize__};
    auto late_opaque_depth = reg.readTexture("late_opaque_depth", gapi::TextureState::DepthReadStencilRead, false);
    auto gibs_surfels_sdf = reg.modifyTexture("gibs_surfels_sdf", gapi::TextureState::ShaderReadWrite);
    auto gibs_surfels_storage = reg.readBuffer("gibs_surfels_storage", gapi::BufferState::BF_STATE_SRV, false);
    auto gibs_surfels_spatial_storage = reg.readBuffer("gibs_surfels_spatial_storage", gapi::BufferState::BF_STATE_SRV, false);
    auto gibs_surfels_allocation_pos = reg.modifyTexture("gibs_surfels_allocation_pos", gapi::TextureState::ShaderReadWrite);
    auto gibs_surfels_lifetime = reg.modifyBuffer("gibs_surfels_lifetime", gapi::BufferState::BF_STATE_UAV_RW);

    return [late_opaque_depth,gibs_surfels_sdf,gibs_surfels_storage,gibs_surfels_spatial_storage,gibs_surfels_allocation_pos,gibs_surfels_lifetime,render_size](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("gbuffer_depth", late_opaque_depth.get());
      tfx::set_extern("surfelsSDF", gibs_surfels_sdf.get());
      tfx::set_extern("surfelsStorage", gibs_surfels_storage.get());
      tfx::set_extern("surfelsSpatialStorage", gibs_surfels_spatial_storage.get());
      tfx::set_extern("surfelsAllocPos", gibs_surfels_allocation_pos.get());
      tfx::set_extern("surfelsLifeTime", gibs_surfels_lifetime.get());
      gibs_surfels_find_surfels_alloc_pos(encoder, render_size.get());
    };
  });
}

static
EventSystemRegistration mk_fg_node_gibs_surfels_find_surfels_alloc_pos_registration(
  mk_fg_node_gibs_surfels_find_surfels_alloc_pos,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_gibs_surfels_find_surfels_alloc_pos"
);
