// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "atmosphere.ecs.cpp" 

using namespace ecs;

const static DirectQueryRegistration query_atmosphere_render_state_queryReg{
  {
    DESCRIBE_QUERY_COMPONENT("atmosphere_render_state", AtmosphereRenderState)
  },
  "query_atmosphere_render_state"};
const static query_id_t query_atmosphere_render_state_queryId = query_atmosphere_render_state_queryReg.getId();


void query_atmosphere_render_state (eastl::function<
  void(
    AtmosphereRenderState& atmosphere_render_state)> cb)
{
  ecs::get_registry().query(query_atmosphere_render_state_queryId, [&](ComponentsAccessor& accessor)
  {
    AtmosphereRenderState& atmosphere_render_state = accessor.get<AtmosphereRenderState>(compile_ecs_name_hash("atmosphere_render_state"));
    cb(atmosphere_render_state);
  });
}


const static DirectQueryRegistration query_atmosphere_queryReg{
  {
    DESCRIBE_QUERY_COMPONENT("atmosphere", AtmosphereComponent)
  },
  "query_atmosphere"};
const static query_id_t query_atmosphere_queryId = query_atmosphere_queryReg.getId();


void query_atmosphere (eastl::function<
  void(
    AtmosphereComponent& atmosphere)> cb)
{
  ecs::get_registry().query(query_atmosphere_queryId, [&](ComponentsAccessor& accessor)
  {
    AtmosphereComponent& atmosphere = accessor.get<AtmosphereComponent>(compile_ecs_name_hash("atmosphere"));
    cb(atmosphere);
  });
}


const static DirectQueryRegistration query_sun_queryReg{
  {
    DESCRIBE_QUERY_COMPONENT("sun", SunComponent)
  },
  "query_sun"};
const static query_id_t query_sun_queryId = query_sun_queryReg.getId();


void query_sun (eastl::function<
  void(
    SunComponent& sun)> cb)
{
  ecs::get_registry().query(query_sun_queryId, [&](ComponentsAccessor& accessor)
  {
    SunComponent& sun = accessor.get<SunComponent>(compile_ecs_name_hash("sun"));
    cb(sun);
  });
}


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_resources(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_resources", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    reg.orderMeAfter("frame_preparing");
    auto camera_data = reg.readBlob<Engine::CameraData>("camera_data");
    auto atm_tr_lut = reg.importTextureProducer("atm_tr_lut", GET_ATM(TrLut));
    auto atm_ms_lut = reg.importTextureProducer("atm_ms_lut", GET_ATM(MsLut));
    auto atm_sky_lut = reg.importTextureProducer("atm_sky_lut", GET_ATM(SkyLut));
    auto atm_ap_lut = reg.importTextureProducer("atm_ap_lut", GET_ATM(ApLut));
    auto atm_envi_specular = reg.importTextureProducer("atm_envi_specular", GET_ATM(EnviSpecular));
    auto atm_envi_brdf = reg.importTextureProducer("atm_envi_brdf", GET_ATM(EnviBRDFLut));
    auto atm_envi_mips = reg.createBlob<int>("atm_envi_mips");
    auto sun_azimuth_altitude = reg.createBlob<float2>("sun_azimuth_altitude");

    return [atm_envi_mips,camera_data,sun_azimuth_altitude](gapi::CmdEncoder& encoder)
    {
      atm_resources_exec(encoder, atm_envi_mips.get(), camera_data.get(), sun_azimuth_altitude.get());
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_resources_registration(
  mk_fg_node_atm_resources,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_resources"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_ap_lut_render(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_ap_lut_render", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto atm_tr_lut = reg.readTexture("atm_tr_lut", gapi::TextureState::ShaderRead, false);
    auto atm_ms_lut = reg.readTexture("atm_ms_lut", gapi::TextureState::ShaderRead, false);
    auto atm_ap_lut = reg.modifyTexture("atm_ap_lut", gapi::TextureState::ShaderReadWrite);

    return [atm_tr_lut,atm_ms_lut,atm_ap_lut](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("trLUT", atm_tr_lut.get());
      tfx::set_extern("msLUT", atm_ms_lut.get());
      tfx::set_extern("apLUT", atm_ap_lut.get());
      atm_ap_lut_render_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_ap_lut_render_registration(
  mk_fg_node_atm_ap_lut_render,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_ap_lut_render"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_tr_lut_render(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_tr_lut_render", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    reg.orderMeAfter("frame_preparing");
    reg.requestRenderPass()
      .addTarget("atm_tr_lut", gapi::LoadOp::DontCare, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
    ;


    return [](gapi::CmdEncoder& encoder)
    {
      atm_tr_lut_render_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_tr_lut_render_registration(
  mk_fg_node_atm_tr_lut_render,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_tr_lut_render"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_ms_lut_render(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_ms_lut_render", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto atm_tr_lut = reg.readTexture("atm_tr_lut", gapi::TextureState::ShaderRead, false);
    reg.requestRenderPass()
      .addTarget("atm_ms_lut", gapi::LoadOp::DontCare, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
    ;


    return [atm_tr_lut](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("trLUT", atm_tr_lut.get());
      atm_ms_lut_render_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_ms_lut_render_registration(
  mk_fg_node_atm_ms_lut_render,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_ms_lut_render"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_sky_lut_render(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_sky_lut_render", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto atm_tr_lut = reg.readTexture("atm_tr_lut", gapi::TextureState::ShaderRead, false);
    auto atm_ms_lut = reg.readTexture("atm_ms_lut", gapi::TextureState::ShaderRead, false);
    reg.requestRenderPass()
      .addTarget("atm_sky_lut", gapi::LoadOp::DontCare, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
    ;


    return [atm_tr_lut,atm_ms_lut](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("trLUT", atm_tr_lut.get());
      tfx::set_extern("msLUT", atm_ms_lut.get());
      atm_sky_lut_render_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_sky_lut_render_registration(
  mk_fg_node_atm_sky_lut_render,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_sky_lut_render"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_sph_render(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_sph_render", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto sph_buf = reg.modifyBuffer("sph_buf", gapi::BufferState::BF_STATE_UAV_RW);
    auto atm_tr_lut = reg.readTexture("atm_tr_lut", gapi::TextureState::ShaderRead, false);
    auto atm_sky_lut = reg.readTexture("atm_sky_lut", gapi::TextureState::ShaderRead, false);

    return [sph_buf,atm_tr_lut,atm_sky_lut](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("atmParamsBuffer", sph_buf.get());
      tfx::set_extern("trLUT", atm_tr_lut.get());
      tfx::set_extern("skyLUT", atm_sky_lut.get());
      atm_sph_render_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_sph_render_registration(
  mk_fg_node_atm_sph_render,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_sph_render"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_sky_apply(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_sky_apply", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto atm_ap_lut = reg.readTexture("atm_ap_lut", gapi::TextureState::ShaderRead, false);
    auto atm_sky_lut = reg.readTexture("atm_sky_lut", gapi::TextureState::ShaderRead, false);
    auto atm_tr_lut = reg.readTexture("atm_tr_lut", gapi::TextureState::ShaderRead, false);
    auto gbuffer_depth = reg.readTexture("gbuffer_depth", gapi::TextureState::DepthReadStencilRead, false);
    reg.requestRenderPass()
      .addTarget("resolve_target", gapi::LoadOp::Load, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
    ;


    return [atm_ap_lut,atm_sky_lut,atm_tr_lut,gbuffer_depth](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("apLUT", atm_ap_lut.get());
      tfx::set_extern("skyLUT", atm_sky_lut.get());
      tfx::set_extern("trLUT", atm_tr_lut.get());
      tfx::set_extern("gbufferDepth", gbuffer_depth.get());
      atm_sky_apply_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_sky_apply_registration(
  mk_fg_node_atm_sky_apply,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_sky_apply"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_envi_specular(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_envi_specular", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto atm_tr_lut = reg.readTexture("atm_tr_lut", gapi::TextureState::ShaderRead, false);
    auto atm_sky_lut = reg.readTexture("atm_sky_lut", gapi::TextureState::ShaderRead, false);
    auto atm_envi_specular = reg.modifyTexture("atm_envi_specular", gapi::TextureState::RenderTarget);
    auto atm_envi_mips = reg.readBlob<int>("atm_envi_mips");

    return [atm_tr_lut,atm_sky_lut,atm_envi_specular,atm_envi_mips](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("trLUT", atm_tr_lut.get());
      tfx::set_extern("skyLUT", atm_sky_lut.get());
      atm_envi_specular_exec(encoder, atm_envi_specular.get(), atm_envi_mips.get());
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_envi_specular_registration(
  mk_fg_node_atm_envi_specular,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_envi_specular"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_envi_brdf(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_envi_brdf", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    reg.requestRenderPass()
      .addTarget("atm_envi_brdf", gapi::LoadOp::DontCare, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
    ;


    return [](gapi::CmdEncoder& encoder)
    {
      atm_envi_brdf_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_envi_brdf_registration(
  mk_fg_node_atm_envi_brdf,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_envi_brdf"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_sync_out(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_sync_out", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    reg.orderMeAfter("frame_preparing");
    auto atm_envi_specular_srv = reg.renameTexture("atm_envi_specular", "atm_envi_specular_srv", gapi::TextureState::ShaderRead);
    auto atm_envi_brdf_srv = reg.renameTexture("atm_envi_brdf", "atm_envi_brdf_srv", gapi::TextureState::ShaderRead);
    auto atm_tr_lut_srv = reg.renameTexture("atm_tr_lut", "atm_tr_lut_srv", gapi::TextureState::ShaderRead);
    auto atm_ms_lut_srv = reg.renameTexture("atm_ms_lut", "atm_ms_lut_srv", gapi::TextureState::ShaderRead);
    auto atm_sky_lut_srv = reg.renameTexture("atm_sky_lut", "atm_sky_lut_srv", gapi::TextureState::ShaderRead);
    auto atm_ap_lut_srv = reg.renameTexture("atm_ap_lut", "atm_ap_lut_srv", gapi::TextureState::ShaderRead);
    return [](gapi::CmdEncoder&){};
  });
}

static
EventSystemRegistration mk_fg_node_atm_sync_out_registration(
  mk_fg_node_atm_sync_out,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_sync_out"
);
