// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "frame_preparing.ecs.cpp" 

using namespace ecs;

const static DirectQueryRegistration query_render_settings_queryReg{
  {
    DESCRIBE_QUERY_COMPONENT("render_window_size", int2)
  },
  "query_render_settings"};
const static query_id_t query_render_settings_queryId = query_render_settings_queryReg.getId();


void query_render_settings (eastl::function<
  void(
    int2 render_window_size)> cb)
{
  ecs::get_registry().query(query_render_settings_queryId, [&](ComponentsAccessor& accessor)
  {
    int2 render_window_size = accessor.get<int2>(compile_ecs_name_hash("render_window_size"));
    cb(render_window_size);
  });
}
