// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "opaque.ecs.cpp" 

using namespace ecs;

const static DirectQueryRegistration query_dynamic_mesh_queryReg{
  {
    DESCRIBE_QUERY_COMPONENT("test_static_mesh_model", string),
    DESCRIBE_QUERY_COMPONENT("test_static_mesh_pos", float3),
    DESCRIBE_QUERY_COMPONENT("test_static_mesh_rot", float3),
    DESCRIBE_QUERY_COMPONENT("test_static_mesh_scale", float3)
  },
  "query_dynamic_mesh"};
const static query_id_t query_dynamic_mesh_queryId = query_dynamic_mesh_queryReg.getId();


void query_dynamic_mesh (eastl::function<
  void(
    const string& test_static_mesh_model,
    const float3& test_static_mesh_pos,
    const float3& test_static_mesh_rot,
    const float3& test_static_mesh_scale)> cb)
{
  ecs::get_registry().query(query_dynamic_mesh_queryId, [&](ComponentsAccessor& accessor)
  {
    const string& test_static_mesh_model = accessor.get<string>(compile_ecs_name_hash("test_static_mesh_model"));
    const float3& test_static_mesh_pos = accessor.get<float3>(compile_ecs_name_hash("test_static_mesh_pos"));
    const float3& test_static_mesh_rot = accessor.get<float3>(compile_ecs_name_hash("test_static_mesh_rot"));
    const float3& test_static_mesh_scale = accessor.get<float3>(compile_ecs_name_hash("test_static_mesh_scale"));
    cb(test_static_mesh_model,test_static_mesh_pos,test_static_mesh_rot,test_static_mesh_scale);
  });
}


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_gbuffer_main_pass(Event*, ComponentsAccessor&)
{
  fg::register_node("gbuffer_main_pass", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    const uint2 __renderSize__ = reg.getRenderSize();

    reg.orderMeAfter("frame_preparing");

    auto opaque_depth = reg.createTexture("opaque_depth",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::D24_UNORM_S8_UINT,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_DEPTH_STENCIL | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::DepthWriteStencilWrite,
      false
    );


    auto gbuf0 = reg.createTexture("gbuf0",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R8G8B8A8_UNORM,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_RT | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::RenderTarget,
      false
    );


    auto gbuf1 = reg.createTexture("gbuf1",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R16G16B16A16_UNORM,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_RT | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::RenderTarget,
      false
    );


    auto gbuf2 = reg.createTexture("gbuf2",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R32G32B32A32_S,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_RT | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::RenderTarget,
      false
    );


    auto motionBuf = reg.createTexture("motionBuf",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R32G32B32A32_S,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_RT | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::RenderTarget,
      false
    );

    reg.requestRenderPass()
      .addTarget(gbuf0, gapi::LoadOp::Clear, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
      .addTarget(gbuf1, gapi::LoadOp::Clear, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
      .addTarget(gbuf2, gapi::LoadOp::Clear, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
      .addTarget(motionBuf, gapi::LoadOp::Clear, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
      .addRWDepth(opaque_depth, gapi::LoadOp::Clear, gapi::StoreOp::Store);


    return [](gapi::CmdEncoder& encoder)
    {
      gbuffer_main_pass_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_gbuffer_main_pass_registration(
  mk_fg_node_gbuffer_main_pass,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_gbuffer_main_pass"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_late_opaque_sync(Event*, ComponentsAccessor&)
{
  fg::register_node("late_opaque_sync", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto late_opaque_depth = reg.renameTexture("opaque_depth", "late_opaque_depth", gapi::TextureState::DepthReadStencilRead);
    return [](gapi::CmdEncoder&){};
  });
}

static
EventSystemRegistration mk_fg_node_late_opaque_sync_registration(
  mk_fg_node_late_opaque_sync,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_late_opaque_sync"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_gbuffer_resolve(Event*, ComponentsAccessor&)
{
  fg::register_node("gbuffer_resolve", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    const uint2 __renderSize__ = reg.getRenderSize();


    auto resolve_target = reg.createTexture("resolve_target",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R32G32B32A32_S,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)((gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_RT | gapi::TextureUsage::TEX_USAGE_UAV) | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::ShaderReadWrite,
      false
    );

    fg::dsl::AccessDecorator render_size{__renderSize__};
    auto gbuf0 = reg.readTexture("gbuf0", gapi::TextureState::ShaderRead, false);
    auto gbuf1 = reg.readTexture("gbuf1", gapi::TextureState::ShaderRead, false);
    auto gbuf2 = reg.readTexture("gbuf2", gapi::TextureState::ShaderRead, false);
    auto post_process_input = reg.readTexture("post_process_input", gapi::TextureState::ShaderRead, fg::Timeline::Previous);
    auto motionBuf = reg.readTexture("motionBuf", gapi::TextureState::ShaderRead, false);
    auto clustered_lights = reg.readBuffer("clustered_lights", gapi::BufferState::BF_STATE_SRV, false);
    auto clusters_info = reg.readBuffer("clusters_info", gapi::BufferState::BF_STATE_SRV, false);
    auto clusters_indirecion = reg.readBuffer("clusters_indirecion", gapi::BufferState::BF_STATE_SRV, false);
    auto gbuffer_depth = reg.renameTexture("late_opaque_depth", "gbuffer_depth", gapi::TextureState::DepthReadStencilRead);
    auto sph_buf = reg.readBuffer("sph_buf", gapi::BufferState::BF_STATE_SRV, false);
    auto indirect_light = reg.readTexture("indirect_light", gapi::TextureState::ShaderRead, false);
    auto specular_light = reg.readTexture("specular_light", gapi::TextureState::ShaderRead, false);

    return [resolve_target,gbuf0,gbuf1,gbuf2,post_process_input,motionBuf,clustered_lights,clusters_info,clusters_indirecion,gbuffer_depth,sph_buf,indirect_light,specular_light,render_size](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("resolveTarget", resolve_target.get());
      tfx::set_extern("gbuffer_albedo", gbuf0.get());
      tfx::set_extern("gbuffer_normal", gbuf1.get());
      tfx::set_extern("gbuffer_metal_roughness", gbuf2.get());
      tfx::set_extern("prevPostProcessInput", post_process_input.get());
      tfx::set_extern("motionBuf", motionBuf.get());
      tfx::set_extern("clustersLightBuffer", clustered_lights.get());
      tfx::set_extern("clustersInfoBuffer", clusters_info.get());
      tfx::set_extern("clustersIndirectionBuffer", clusters_indirecion.get());
      tfx::set_extern("gbuffer_depth", gbuffer_depth.get());
      tfx::set_extern("atmParamsBuffer", sph_buf.get());
      tfx::set_extern("indirectLight", indirect_light.get());
      tfx::set_extern("specularLight", specular_light.get());
      gbuffer_resolve_exec(encoder, render_size.get());
    };
  });
}

static
EventSystemRegistration mk_fg_node_gbuffer_resolve_registration(
  mk_fg_node_gbuffer_resolve,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_gbuffer_resolve"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_post_opaque_sync(Event*, ComponentsAccessor&)
{
  fg::register_node("post_opaque_sync", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto post_opaque_target = reg.renameTexture("resolve_target", "post_opaque_target", gapi::TextureState::RenderTarget);
    return [](gapi::CmdEncoder&){};
  });
}

static
EventSystemRegistration mk_fg_node_post_opaque_sync_registration(
  mk_fg_node_post_opaque_sync,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_post_opaque_sync"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_transparent_sync(Event*, ComponentsAccessor&)
{
  fg::register_node("transparent_sync", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto transparent_target = reg.renameTexture("taa_target", "transparent_target", gapi::TextureState::RenderTarget);
    return [](gapi::CmdEncoder&){};
  });
}

static
EventSystemRegistration mk_fg_node_transparent_sync_registration(
  mk_fg_node_transparent_sync,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_transparent_sync"
);
