// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "post_process.ecs.cpp" 

using namespace ecs;

static void mk_post_process_node_internal(Event* event, ComponentsAccessor& accessor)
{
  const Engine::OnFrameGraphInit* casted_event = reinterpret_cast<const Engine::OnFrameGraphInit*>(event);

  mk_post_process_node(*casted_event);
}


static EventSystemRegistration mk_post_process_node_registration(
  mk_post_process_node_internal,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {

  },
  "mk_post_process_node"
);
