// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "post_transparent.ecs.cpp" 

using namespace ecs;

static void mk_ui_node_internal(Event* event, ComponentsAccessor& accessor)
{
  const Engine::OnFrameGraphInit* casted_event = reinterpret_cast<const Engine::OnFrameGraphInit*>(event);

  mk_ui_node(*casted_event);
}


static EventSystemRegistration mk_ui_node_registration(
  mk_ui_node_internal,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {

  },
  "mk_ui_node"
);


static void mk_dbg_text_node_internal(Event* event, ComponentsAccessor& accessor)
{
  const Engine::OnFrameGraphInit* casted_event = reinterpret_cast<const Engine::OnFrameGraphInit*>(event);

  mk_dbg_text_node(*casted_event);
}


static EventSystemRegistration mk_dbg_text_node_registration(
  mk_dbg_text_node_internal,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {

  },
  "mk_dbg_text_node"
);


static void mk_taa_node_internal(Event* event, ComponentsAccessor& accessor)
{
  const Engine::OnFrameGraphInit* casted_event = reinterpret_cast<const Engine::OnFrameGraphInit*>(event);

  mk_taa_node(*casted_event);
}


static EventSystemRegistration mk_taa_node_registration(
  mk_taa_node_internal,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {

  },
  "mk_taa_node"
);


static void mk_present_node_internal(Event* event, ComponentsAccessor& accessor)
{
  const Engine::OnFrameGraphInit* casted_event = reinterpret_cast<const Engine::OnFrameGraphInit*>(event);

  mk_present_node(*casted_event);
}


static EventSystemRegistration mk_present_node_registration(
  mk_present_node_internal,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {

  },
  "mk_present_node"
);
