// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "ui.ecs.cpp" 

using namespace ecs;

//Engine::OnFrameGraphInit handler
static
void mk_fg_node_ui(Event*, ComponentsAccessor&)
{
  fg::register_node("ui", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    reg.requestRenderPass()
      .addTarget("final_target", gapi::LoadOp::Load, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
    ;


    return [](gapi::CmdEncoder& encoder)
    {
      ui_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_ui_registration(
  mk_fg_node_ui,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_ui"
);
