// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "imgui_sun.ecs.cpp" 

using namespace ecs;

const static DirectQueryRegistration query_sun_queryReg{
  {
    DESCRIBE_QUERY_COMPONENT("sun", SunComponent)
  },
  "query_sun"};
const static query_id_t query_sun_queryId = query_sun_queryReg.getId();


void query_sun (eastl::function<
  void(
    SunComponent& sun)> cb)
{
  ecs::get_registry().query(query_sun_queryId, [&](ComponentsAccessor& accessor)
  {
    SunComponent& sun = accessor.get<SunComponent>(compile_ecs_name_hash("sun"));
    cb(sun);
  });
}
