// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "sky_apply.ecs.cpp" 

using namespace ecs;

//Engine::OnFrameGraphInit handler
static
void mk_fg_node_atm_sky_apply(Event*, ComponentsAccessor&)
{
  fg::register_node("atm_sky_apply", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto atm_ap_lut = reg.readTexture("atm_ap_lut", gapi::TextureState::ShaderRead, false);
    auto atm_sky_lut = reg.readTexture("atm_sky_lut", gapi::TextureState::ShaderRead, false);
    auto atm_tr_lut = reg.readTexture("atm_tr_lut", gapi::TextureState::ShaderRead, false);
    auto gbuffer_depth = reg.readTexture("gbuffer_depth", gapi::TextureState::DepthReadStencilRead, false);
    reg.requestRenderPass()
      .addTarget("resolve_target", gapi::LoadOp::Load, gapi::StoreOp::Store, gapi::ClearColorValue{uint32_t{0}})
    ;


    return [atm_ap_lut,atm_sky_lut,atm_tr_lut,gbuffer_depth](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("apLUT", atm_ap_lut.get());
      tfx::set_extern("skyLUT", atm_sky_lut.get());
      tfx::set_extern("trLUT", atm_tr_lut.get());
      tfx::set_extern("gbufferDepth", gbuffer_depth.get());
      atm_sky_apply_exec(encoder);
    };
  });
}

static
EventSystemRegistration mk_fg_node_atm_sky_apply_registration(
  mk_fg_node_atm_sky_apply,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_atm_sky_apply"
);
