// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "reflections.ecs.cpp" 

using namespace ecs;

//Engine::OnFrameGraphInit handler
static
void mk_fg_node_reflections_resources(Event*, ComponentsAccessor&)
{
  fg::register_node("reflections_resources", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    const uint2 __renderSize__ = reg.getRenderSize();


    auto reflections_target = reg.createTexture("reflections_target",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R32G32B32A32_S,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_UAV | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::ShaderReadWrite,
      false
    );


    auto reflections_acc = reg.createTexture("reflections_acc",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R32G32B32A32_S,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_UAV | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::ShaderReadWrite,
      false
    );


    auto reflections_variance = reg.createTexture("reflections_variance",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R8_UNORM,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_UAV | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::ShaderReadWrite,
      false
    );


    auto reflections_target_filtered = reg.createTexture("reflections_target_filtered",
      gapi::TextureAllocationDescription{
        .format =          gapi::TextureFormat::R32G32B32A32_S,
        .extent =          uint3(__renderSize__, 1),
        .mipLevels =       1,
        .arrayLayers =     1,
        .samplesPerPixel = gapi::TextureSamples::s1,
        .usage =           (gapi::TextureUsage)(gapi::TextureUsage::TEX_USAGE_UAV | gapi::TextureUsage::TEX_USAGE_SRV)
      },
      gapi::TextureState::ShaderReadWrite,
      false
    );


    return [reflections_target,reflections_acc,reflections_variance,reflections_target_filtered](gapi::CmdEncoder& encoder)
    {
      reflections_resources(encoder, reflections_target.get(), reflections_acc.get(), reflections_variance.get(), reflections_target_filtered.get());
    };
  });
}

static
EventSystemRegistration mk_fg_node_reflections_resources_registration(
  mk_fg_node_reflections_resources,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_reflections_resources"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_reflections(Event*, ComponentsAccessor&)
{
  fg::register_node("reflections", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    const uint2 __renderSize__ = reg.getRenderSize();

    fg::dsl::AccessDecorator render_size{__renderSize__};
    auto reflections_target = reg.modifyTexture("reflections_target", gapi::TextureState::ShaderReadWrite);
    auto gbuf0 = reg.readTexture("gbuf0", gapi::TextureState::ShaderRead, false);
    auto gbuf1 = reg.readTexture("gbuf1", gapi::TextureState::ShaderRead, false);
    auto gbuf2 = reg.readTexture("gbuf2", gapi::TextureState::ShaderRead, false);
    auto post_process_input = reg.readTexture("post_process_input", gapi::TextureState::ShaderRead, fg::Timeline::Previous);
    auto motionBuf = reg.readTexture("motionBuf", gapi::TextureState::ShaderRead, false);
    auto late_opaque_depth = reg.readTexture("late_opaque_depth", gapi::TextureState::DepthReadStencilRead, false);
    auto hi_z_buffer = reg.readTexture("hi_z_buffer", gapi::TextureState::ShaderRead, false);
    auto atm_envi_specular_srv = reg.readTexture("atm_envi_specular_srv", gapi::TextureState::ShaderRead, true);
    auto atm_envi_brdf_srv = reg.readTexture("atm_envi_brdf_srv", gapi::TextureState::ShaderRead, true);

    return [reflections_target,gbuf0,gbuf1,gbuf2,post_process_input,motionBuf,late_opaque_depth,hi_z_buffer,atm_envi_specular_srv,atm_envi_brdf_srv,render_size](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("reflectionsTarget", reflections_target.get());
      tfx::set_extern("gbuffer_albedo", gbuf0.get());
      tfx::set_extern("gbuffer_normal", gbuf1.get());
      tfx::set_extern("gbuffer_metal_roughness", gbuf2.get());
      tfx::set_extern("prevPostProcessInput", post_process_input.get());
      tfx::set_extern("motionBuf", motionBuf.get());
      tfx::set_extern("gbuffer_depth", late_opaque_depth.get());
      tfx::set_extern("hi_z_buffer", hi_z_buffer.get());
      tfx::set_extern("enviSpecular", atm_envi_specular_srv.get());
      tfx::set_extern("enviBRDF", atm_envi_brdf_srv.get());
      reflections(encoder, render_size.get());
    };
  });
}

static
EventSystemRegistration mk_fg_node_reflections_registration(
  mk_fg_node_reflections,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_reflections"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_reflections_temporal_acc(Event*, ComponentsAccessor&)
{
  fg::register_node("reflections_temporal_acc", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    const uint2 __renderSize__ = reg.getRenderSize();

    fg::dsl::AccessDecorator render_size{__renderSize__};
    auto motionBuf = reg.readTexture("motionBuf", gapi::TextureState::ShaderRead, false);
    auto reflections_target = reg.readTexture("reflections_target", gapi::TextureState::ShaderRead, false);
    auto reflections_target_filtered = reg.readTexture("reflections_target_filtered", gapi::TextureState::ShaderRead, fg::Timeline::Previous);
    auto reflections_variance_prev = reg.readTexture("reflections_variance", gapi::TextureState::ShaderRead, fg::Timeline::Previous);
    auto reflections_variance_cur = reg.modifyTexture("reflections_variance", gapi::TextureState::ShaderReadWrite);
    auto reflections_acc = reg.modifyTexture("reflections_acc", gapi::TextureState::ShaderReadWrite);
    auto late_opaque_depth = reg.readTexture("late_opaque_depth", gapi::TextureState::DepthReadStencilRead, false);

    return [motionBuf,reflections_target,reflections_target_filtered,reflections_variance_prev,reflections_variance_cur,reflections_acc,late_opaque_depth,render_size](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("motionBuf", motionBuf.get());
      tfx::set_extern("taInput", reflections_target.get());
      tfx::set_extern("taHistory", reflections_target_filtered.get());
      tfx::set_extern("taVarianceHistory", reflections_variance_prev.get());
      tfx::set_extern("taVarianceOutput", reflections_variance_cur.get());
      tfx::set_extern("taOutput", reflections_acc.get());
      tfx::set_extern("gbuffer_depth", late_opaque_depth.get());
      reflections_temporal_acc(encoder, render_size.get());
    };
  });
}

static
EventSystemRegistration mk_fg_node_reflections_temporal_acc_registration(
  mk_fg_node_reflections_temporal_acc,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_reflections_temporal_acc"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_reflections_blur(Event*, ComponentsAccessor&)
{
  fg::register_node("reflections_blur", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    const uint2 __renderSize__ = reg.getRenderSize();

    fg::dsl::AccessDecorator render_size{__renderSize__};
    auto reflections_acc = reg.readTexture("reflections_acc", gapi::TextureState::ShaderRead, false);
    auto reflections_target_filtered = reg.modifyTexture("reflections_target_filtered", gapi::TextureState::ShaderReadWrite);
    auto gbuf2 = reg.readTexture("gbuf2", gapi::TextureState::ShaderRead, false);
    auto reflections_variance = reg.readTexture("reflections_variance", gapi::TextureState::ShaderRead, false);

    return [reflections_acc,reflections_target_filtered,gbuf2,reflections_variance,render_size](gapi::CmdEncoder& encoder)
    {
      tfx::set_extern("blurInput", reflections_acc.get());
      tfx::set_extern("blurOutput", reflections_target_filtered.get());
      tfx::set_extern("gbuffer_metal_roughness", gbuf2.get());
      tfx::set_extern("taVariance", reflections_variance.get());
      reflections_blur(encoder, render_size.get());
    };
  });
}

static
EventSystemRegistration mk_fg_node_reflections_blur_registration(
  mk_fg_node_reflections_blur,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_reflections_blur"
);


//Engine::OnFrameGraphInit handler
static
void mk_fg_node_reflections_sync(Event*, ComponentsAccessor&)
{
  fg::register_node("reflections_sync", FG_FILE_DECL, [](fg::Registry& reg)
  { 
    auto specular_light = reg.renameTexture("reflections_target_filtered", "specular_light", gapi::TextureState::ShaderRead);
    return [](gapi::CmdEncoder&){};
  });
}

static
EventSystemRegistration mk_fg_node_reflections_sync_registration(
  mk_fg_node_reflections_sync,
  compile_ecs_name_hash("OnFrameGraphInit"),
  {
  },
  "mk_fg_node_reflections_sync"
);
