// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "render.ecs.cpp" 

using namespace ecs;

const static DirectQueryRegistration query_line_renderer_queryReg{
  {
    DESCRIBE_QUERY_COMPONENT("dbg_line_renderer", Engine::dbg::LineRenderer)
  },
  "query_line_renderer"};
const static query_id_t query_line_renderer_queryId = query_line_renderer_queryReg.getId();


void query_line_renderer (eastl::function<
  void(
    Engine::dbg::LineRenderer& dbg_line_renderer)> cb)
{
  ecs::get_registry().query(query_line_renderer_queryId, [&](ComponentsAccessor& accessor)
  {
    Engine::dbg::LineRenderer& dbg_line_renderer = accessor.get<Engine::dbg::LineRenderer>(compile_ecs_name_hash("dbg_line_renderer"));
    cb(dbg_line_renderer);
  });
}


const static DirectQueryRegistration query_poly_renderer_queryReg{
  {
    DESCRIBE_QUERY_COMPONENT("dbg_poly_renderer", Engine::dbg::PolyRenderer)
  },
  "query_poly_renderer"};
const static query_id_t query_poly_renderer_queryId = query_poly_renderer_queryReg.getId();


void query_poly_renderer (eastl::function<
  void(
    Engine::dbg::PolyRenderer& dbg_poly_renderer)> cb)
{
  ecs::get_registry().query(query_poly_renderer_queryId, [&](ComponentsAccessor& accessor)
  {
    Engine::dbg::PolyRenderer& dbg_poly_renderer = accessor.get<Engine::dbg::PolyRenderer>(compile_ecs_name_hash("dbg_poly_renderer"));
    cb(dbg_poly_renderer);
  });
}
