// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/registry.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "gui.ecs.cpp" 

using namespace Engine::ECS;

static void camera_rotation_internal(ComponentsAccessor& accessor)
{
  const float2& camera_rotations = accessor.get<float2>(str_hash("camera_rotations"));
  camera_rotation(camera_rotations);
}


static SystemRegistration camera_rotation_registration(
  camera_rotation_internal,
  {
    DESCRIBE_QUERY_COMPONENT("camera_rotations", float2)
  }
);


static void input_handler_internal(Event* event, ComponentsAccessor& accessor)
{
  ButtonActionInputEvent* casted_event = reinterpret_cast<ButtonActionInputEvent*>(event);

  input_handler(*casted_event);
}


static EventSystemRegistration input_handler_registration(
  input_handler_internal,
  str_hash("ButtonActionInputEvent"),
  {

  }
);


static void system_test_multiple_templates_internal(ComponentsAccessor& accessor)
{
  const float& test_float = accessor.get<float>(str_hash("test_float"));
  const string& test_str = accessor.get<string>(str_hash("test_str"));
  float2 test_float2 = accessor.get<float2>(str_hash("test_float2"));
  float3 test_float3 = accessor.get<float3>(str_hash("test_float3"));
  system_test_multiple_templates(test_float,test_str,test_float2,test_float3);
}


static SystemRegistration system_test_multiple_templates_registration(
  system_test_multiple_templates_internal,
  {
    DESCRIBE_QUERY_COMPONENT("test_float", float),
    DESCRIBE_QUERY_COMPONENT("test_str", string),
    DESCRIBE_QUERY_COMPONENT("test_float2", float2),
    DESCRIBE_QUERY_COMPONENT("test_float3", float3)
  }
);


static void system_test_multiple_templates2_internal(ComponentsAccessor& accessor)
{
  const string& test_str = accessor.get<string>(str_hash("test_str"));
  float2 test_float2 = accessor.get<float2>(str_hash("test_float2"));
  system_test_multiple_templates2(test_str,test_float2);
}


static SystemRegistration system_test_multiple_templates2_registration(
  system_test_multiple_templates2_internal,
  {
    DESCRIBE_QUERY_COMPONENT("test_str", string),
    DESCRIBE_QUERY_COMPONENT("test_float2", float2)
  }
);
