// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/registry.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "test_query.ecs.cpp" 

  const static query_id query_queryId = Registry::register_direct_query(
    DirectQueryDescription{
      .components = {
         DESCRIBE_QUERY_COMPONENT("test_float2", Float2)
      }
    }
  );
  

  static void query (eastl::function<void( const Float2& test_float2)> cb)
  {
    ecs.query(query_queryId, [&](ComponentsAccessor& accessor)
    {
       const Float2& test_float2 = accessor.Get<Float2>(str_hash("test_float2")) ;
      cb(test_float2);
    });
  }
  

static void system_test_internal(ComponentsAccessor& accessor)
{
   const float& test_float = accessor.Get<float>(str_hash("test_float")) ;
  system_test(test_float);
}
  

static const bool system_test_desc = Registry::register_cpp_query(
  QueryDescription{
    .cb = system_test_internal,
    .components = {
       DESCRIBE_QUERY_COMPONENT("test_float", float)
    }
  }
);
  

static void system_with_query_internal(ComponentsAccessor& accessor)
{
   const float& test_float = accessor.Get<float>(str_hash("test_float")) ;
  system_with_query(test_float);
}
  

static const bool system_with_query_desc = Registry::register_cpp_query(
  QueryDescription{
    .cb = system_with_query_internal,
    .components = {
       DESCRIBE_QUERY_COMPONENT("test_float", float)
    }
  }
);
  