#ifndef BINDLESS_MATERIAL_IDS_HLSL
#define BINDLESS_MATERIAL_IDS_HLSL

#define BINDLESS_MATERIAL_ALBEDO_TEX           uint(0)
#define BINDLESS_MATERIAL_NORMAL_TEX           uint(1)
#define BINDLESS_MATERIAL_METAL_ROUGHNESS_TEX  uint(2)
#define BINDLESS_MATERIAL_TEX_COUNT            uint(BINDLESS_MATERIAL_METAL_ROUGHNESS_TEX+1)

#endif