import clang.cindex
import os

ES_SYSTEM_TAG = "ecs_system"
ES_EVENT_SYSTEM_TAG = "ecs_event_system"
ES_QUERY_TAG = "ecs_query"
FG_EXEC_TAG = "fg_node_exec"
FG_DSL_TAG = "fg_node_dsl"

import parsed_types_ecs as parsed_ecs
import parsed_types_fg as parsed_fg

def generate_ecs_impl(from_src, includeArgs, defineArgs):
  generated_code = [
    "// this file is generated by ecs codegen",
    "// do not edit",
    "#include <engine/ecs/ecs.h>",
    "#include <engine/ecs/components_accessor.h>",
    "#include <EASTL/functional.h>",
    "",
    """#include "{}" """.format(os.path.basename(from_src)),
    "",
    "using namespace ecs;"
  ]

  index = clang.cindex.Index.create()
  clangArgs = ["-x", "c++", "--std=c++20"] + includeArgs + defineArgs

  translation_unit = index.parse(from_src, clangArgs)

  errors = []
  for d in translation_unit.diagnostics:
    if d.severity >= clang.cindex.Diagnostic.Error:
      errors = errors + ["error({}): {} [at {}]".format(d.severity, d.spelling, d.location)]

  if len(errors) > 0:
    raise ValueError("\n".join(map(str,errors)))

  fgExecFnCursors = {}
  generators = []

  for fnCursor in translation_unit.cursor.get_children():
    if fnCursor.kind == clang.cindex.CursorKind.FUNCTION_DECL:
      paramCursors = []
      isEsSystem = False
      isEsEventSystem = False
      isEsQuery = False
      isFgExec = False

      for child in fnCursor.get_children():
        if child.kind == clang.cindex.CursorKind.PARM_DECL:
          paramCursors = paramCursors + [child]
        elif child.kind == clang.cindex.CursorKind.ANNOTATE_ATTR:
          if child.spelling == ES_SYSTEM_TAG:
            isEsSystem = True
          elif child.spelling == ES_EVENT_SYSTEM_TAG:
            isEsEventSystem = True
          elif child.spelling == ES_QUERY_TAG:
            isEsQuery = True
          elif child.spelling == FG_EXEC_TAG:
            isFgExec = True

      if isEsQuery:
        generators = generators + [parsed_ecs.Query(fnCursor, paramCursors)]
      elif isEsSystem:
        generators = generators + [parsed_ecs.System(fnCursor, paramCursors)]
      elif isEsEventSystem:
        generators = generators + [parsed_ecs.EventSystem(fnCursor, paramCursors)]
      elif isFgExec:
        fgExecFnCursors[fnCursor.spelling] = (fnCursor, paramCursors)

    elif fnCursor.kind == clang.cindex.CursorKind.STRUCT_DECL:
      for child in fnCursor.get_children():
        if child.kind == clang.cindex.CursorKind.ANNOTATE_ATTR and child.spelling == FG_DSL_TAG:
          generators = generators + [parsed_fg.FgNode(fnCursor, fgExecFnCursors)]

  generated_code.extend([g.generate() for g in generators])
  final_src = '\n'.join(generated_code)

  return final_src
