// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "model_render.ecs.cpp" 

using namespace ecs;

const static DirectQueryRegistration query_static_mesh_queryReg{
  {
    DESCRIBE_QUERY_COMPONENT("static_mesh", StaticMeshComponent)
  },
  "query_static_mesh"};
const static query_id_t query_static_mesh_queryId = query_static_mesh_queryReg.getId();


void query_static_mesh (eastl::function<
  void(
    const StaticMeshComponent& static_mesh)> cb)
{
  ecs::get_registry().query(query_static_mesh_queryId, [&](ComponentsAccessor& accessor)
  {
    const StaticMeshComponent& static_mesh = accessor.get<StaticMeshComponent>(compile_ecs_name_hash("static_mesh"));
    cb(static_mesh);
  });
}
