// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "camera.ecs.cpp" 

using namespace ecs;

static void camera_movement_internal(ComponentsAccessor& accessor)
{
  float3& pos = accessor.get<float3>(compile_ecs_name_hash("pos"));
  const float2& camera_rotations = accessor.get<float2>(compile_ecs_name_hash("camera_rotations"));
  const float3& forward = accessor.get<float3>(compile_ecs_name_hash("forward"));
  camera_movement(pos,camera_rotations,forward);
}


static SystemRegistration camera_movement_registration(
  camera_movement_internal,
  {
    DESCRIBE_QUERY_COMPONENT("pos", float3),
    DESCRIBE_QUERY_COMPONENT("camera_rotations", float2),
    DESCRIBE_QUERY_COMPONENT("forward", float3)
  },
  "camera_movement"
);


static void camera_rotation_internal(ComponentsAccessor& accessor)
{
  float2& camera_rotations = accessor.get<float2>(compile_ecs_name_hash("camera_rotations"));
  float3& forward = accessor.get<float3>(compile_ecs_name_hash("forward"));
  camera_rotation(camera_rotations,forward);
}


static SystemRegistration camera_rotation_registration(
  camera_rotation_internal,
  {
    DESCRIBE_QUERY_COMPONENT("camera_rotations", float2),
    DESCRIBE_QUERY_COMPONENT("forward", float3)
  },
  "camera_rotation"
);
