// this file is generated by ecs codegen
// do not edit
#include <engine/ecs/ecs.h>
#include <engine/ecs/components_accessor.h>
#include <EASTL/functional.h>

#include "camera.ecs.cpp" 

using namespace ecs;

static void camera_movement_internal(ComponentsAccessor& accessor)
{
  CameraComponent& camera = accessor.get<CameraComponent>(compile_ecs_name_hash("camera"));
  camera_movement(camera);
}


static SystemRegistration camera_movement_registration(
  camera_movement_internal,
  {
    DESCRIBE_QUERY_COMPONENT("camera", CameraComponent)
  },
  "camera_movement"
);


static void camera_rotation_internal(ComponentsAccessor& accessor)
{
  CameraComponent& camera = accessor.get<CameraComponent>(compile_ecs_name_hash("camera"));
  camera_rotation(camera);
}


static SystemRegistration camera_rotation_registration(
  camera_rotation_internal,
  {
    DESCRIBE_QUERY_COMPONENT("camera", CameraComponent)
  },
  "camera_rotation"
);
